package com.libdbm.xml;

import com.libdbm.ugf.parser.ParseTree;
import com.libdbm.ugf.parser.Utilities;
import com.libdbm.xml.XMLNode.*;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/** Builds XML AST from unification grammar parse trees */
public final class XMLBuilder {

  private final String input;

  private XMLBuilder(final String input) {
    this.input = input;
  }

  /**
   * Check if symbol is an auxiliary generated by grammar normalization (e.g., foo_plus_0,
   * bar_star_1)
   */
  private static boolean isAux(final String symbol) {
    return symbol.matches(".*_(plus|star|opt)_\\d+$");
  }

  public static XMLNode build(final ParseTree tree) {
    throw new IllegalArgumentException(
        "XMLBuilder requires original input. Use build(tree, input) instead.");
  }

  public static XMLNode build(final ParseTree tree, final String input) {
    if (input == null) {
      throw new IllegalArgumentException("Original input is required for XMLBuilder");
    }
    final XMLBuilder builder = new XMLBuilder(input);
    return builder.buildTree(tree);
  }

  private XMLNode buildTree(final ParseTree tree) {
    return switch (tree) {
      case ParseTree.Leaf leaf ->
          throw new IllegalArgumentException("Cannot build from leaf: " + leaf);
      case ParseTree.Node node ->
          switch (node.symbol()) {
            case "document" -> buildDocument(node);
            case "element" -> buildElement(node);
            case "normal_element" -> buildNormalElement(node);
            case "empty_element" -> buildEmptyElement(node);
            default -> throw new IllegalArgumentException("Unknown symbol: " + node.symbol());
          };
    };
  }

  private XMLNode buildDocument(final ParseTree.Node node) {
    // document --> element
    for (final var child : node.children()) {
      if (child instanceof ParseTree.Node n && n.symbol().equals("element")) {
        return buildElement(n);
      }
    }
    throw new IllegalArgumentException("Invalid document node: " + node);
  }

  private XMLNode buildElement(final ParseTree.Node node) {
    // element --> normal_element | empty_element
    for (final var child : node.children()) {
      if (child instanceof ParseTree.Node n) {
        return switch (n.symbol()) {
          case "normal_element" -> buildNormalElement(n);
          case "empty_element" -> buildEmptyElement(n);
          default -> throw new IllegalArgumentException("Unknown element type: " + n.symbol());
        };
      }
    }
    throw new IllegalArgumentException("Invalid element node: " + node);
  }

  private XMLNode buildNormalElement(final ParseTree.Node node) {
    // normal_element --> '<' tagname '>' content '<' '/' tagname '>'
    // normal_element --> '<' tagname attributes '>' content '<' '/' tagname '>'

    String tag = null;
    Map<String, String> attributes = new LinkedHashMap<>();
    Content content = null;

    for (final var child : node.children()) {
      if (child instanceof ParseTree.Node n) {
        final var sym = n.symbol();
        if (sym.equals("tagname")) {
          if (tag == null) {
            tag = getLeafText(n);
          }
        } else if (sym.equals("attributes") || sym.startsWith("attribute") && isAux(sym)) {
          attributes = buildAttributes(n);
        } else if (sym.equals("content") || sym.startsWith("content") && isAux(sym)) {
          content = buildContent(n);
        }
      }
    }

    if (tag == null) {
      throw new IllegalArgumentException("Missing tag name in normal_element: " + node);
    }
    if (content == null) {
      throw new IllegalArgumentException("Missing content in normal_element: " + node);
    }

    return new Element(tag, attributes, content);
  }

  private XMLNode buildEmptyElement(final ParseTree.Node node) {
    // empty_element --> '<' tagname '/' '>'
    // empty_element --> '<' tagname attributes '/' '>'

    String tag = null;
    Map<String, String> attributes = new LinkedHashMap<>();

    for (final var child : node.children()) {
      if (child instanceof ParseTree.Node n) {
        final var sym = n.symbol();
        if (sym.equals("tagname")) {
          tag = getLeafText(n);
        } else if (sym.equals("attributes") || sym.startsWith("attribute") && isAux(sym)) {
          attributes = buildAttributes(n);
        }
      }
    }

    if (tag == null) {
      throw new IllegalArgumentException("Missing tag name in empty_element: " + node);
    }

    return new EmptyElement(tag, attributes);
  }

  private Map<String, String> buildAttributes(final ParseTree.Node node) {
    // attributes --> ws? attribute ws_attr*
    // ws_attr --> ws attribute
    final var attrs = new LinkedHashMap<String, String>();

    for (final var child : node.children()) {
      if (child instanceof ParseTree.Node n) {
        final var sym = n.symbol();
        if (sym.equals("attribute")) {
          final var attr = buildAttribute(n);
          attrs.put(attr.getKey(), attr.getValue());
        } else if (sym.equals("ws_attr")) {
          // ws_attr contains ws + attribute
          attrs.putAll(buildAttributes(n));
        } else if (isAux(sym)) {
          attrs.putAll(buildAttributes(n));
        }
      }
    }

    return attrs;
  }

  private Map.Entry<String, String> buildAttribute(final ParseTree.Node node) {
    // attribute --> attrname '=' attrvalue

    String name = null;
    String value = null;

    for (final var child : node.children()) {
      if (child instanceof ParseTree.Node n) {
        switch (n.symbol()) {
          case "attrname" -> name = getLeafText(n);
          case "attrvalue" -> value = buildAttrValue(n);
        }
      }
    }

    if (name == null || value == null) {
      throw new IllegalArgumentException("Invalid attribute: " + node);
    }

    return Map.entry(name, value);
  }

  private String buildAttrValue(final ParseTree.Node node) {
    // attrvalue --> '"' stringcontent '"'
    // attrvalue --> '"' '"'

    for (final var child : node.children()) {
      if (child instanceof ParseTree.Node n) {
        final var sym = n.symbol();
        if (sym.equals("stringcontent")
            || sym.startsWith("stringcontent") && isAux(sym)
            || sym.startsWith("stringpart") && isAux(sym)) {
          return buildStringContent(n);
        }
      }
    }

    // Empty attribute value (just quotes)
    return "";
  }

  private String buildStringContent(final ParseTree.Node node) {
    // stringcontent --> stringpart+
    // Concatenate tokens with spaces between alphanumeric words only
    final var sb = new StringBuilder();
    boolean first = true;
    String lastToken = null;

    for (final var child : node.children()) {
      if (child instanceof ParseTree.Node n) {
        final var sym = n.symbol();
        if (sym.equals("stringpart") || sym.equals("char_ref") || sym.equals("entity_ref")) {
          final var text = getLeafText(n);
          final var isAlphaNum = text.matches("[a-zA-Z0-9_\\-]+");
          final var lastWasAlphaNum = lastToken != null && lastToken.matches("[a-zA-Z0-9_\\-]+");

          // Add space between two alphanumeric words
          if (!first && isAlphaNum && lastWasAlphaNum) {
            sb.append(" ");
          }

          sb.append(text);
          lastToken = text;
          first = false;
        } else if (isAux(sym)) {
          sb.append(buildStringContent(n));
        }
      }
    }

    return sb.toString();
  }

  private Content buildContent(final ParseTree.Node node) {
    // content --> content_item+
    // content_item --> textcontent | cdata_section | element

    final var items = new ArrayList<XMLNode.ContentItem>();

    for (final var child : node.children()) {
      if (child instanceof ParseTree.Node n) {
        final var sym = n.symbol();
        if (sym.equals("content_item")) {
          items.add(buildContentItem(n));
        } else if (isAux(sym)) {
          // Handle auxiliary repetition nodes
          items.addAll(buildContentItems(n));
        }
      }
    }

    if (items.isEmpty()) {
      throw new IllegalArgumentException("Invalid content node - no items: " + node);
    }

    // Optimize: if all items are of same type, use simple Content types
    if (items.stream().allMatch(i -> i instanceof XMLNode.ContentItem.Text)) {
      // All text - concatenate
      final String combined =
          items.stream()
              .map(i -> ((XMLNode.ContentItem.Text) i).value())
              .collect(java.util.stream.Collectors.joining(" "));
      return new Content.Text(combined);
    } else if (items.size() == 1 && items.getFirst() instanceof ContentItem.CDATA(String value)) {
      return new Content.CDATA(value);
    } else if (items.stream().allMatch(i -> i instanceof XMLNode.ContentItem.Element)) {
      // All elements
      final var nodes =
          items.stream()
              .map(i -> ((XMLNode.ContentItem.Element) i).node())
              .collect(java.util.stream.Collectors.toList());
      return new Content.Elements(nodes);
    }

    // Mixed content
    return new Content.Mixed(items);
  }

  private XMLNode.ContentItem buildContentItem(final ParseTree.Node node) {
    // content_item --> textcontent | cdata_section | comment | element

    for (final var child : node.children()) {
      if (child instanceof ParseTree.Node n) {
        final var sym = n.symbol();
        if (sym.equals("textcontent")
            || sym.startsWith("textcontent") && isAux(sym)
            || sym.startsWith("textpart") && isAux(sym)) {
          return new XMLNode.ContentItem.Text(buildTextContent(n));
        } else if (sym.equals("cdata_section")) {
          final var cdata = buildCdataSection(n);
          return new XMLNode.ContentItem.CDATA(cdata.value());
        } else if (sym.equals("comment")) {
          return new XMLNode.ContentItem.Comment(buildComment(n));
        } else if (sym.equals("element")) {
          return new XMLNode.ContentItem.Element(buildElement(n));
        }
      }
    }

    throw new IllegalArgumentException("Invalid content_item node: " + node);
  }

  private List<XMLNode.ContentItem> buildContentItems(final ParseTree.Node node) {
    final var items = new ArrayList<XMLNode.ContentItem>();

    for (final var child : node.children()) {
      if (child instanceof ParseTree.Node n) {
        final var sym = n.symbol();
        if (sym.equals("content_item")) {
          items.add(buildContentItem(n));
        } else if (isAux(sym)) {
          items.addAll(buildContentItems(n));
        }
      }
    }

    return items;
  }

  private Content.CDATA buildCdataSection(final ParseTree.Node node) {
    // cdata_section --> '<![CDATA[' cdata_content ']]>'
    // cdata_section --> '<![CDATA[' ']]>'

    // Extract content between <![CDATA[ and ]]> markers
    for (final var child : node.children()) {
      if (child instanceof ParseTree.Node n) {
        final var sym = n.symbol();
        if (sym.equals("cdata_content") || sym.startsWith("cdata_content") && isAux(sym)) {
          // Concatenate all tokens without spaces (no normalization)
          return new Content.CDATA(buildCdataContent(n));
        }
      }
    }

    // Empty CDATA
    return new Content.CDATA("");
  }

  private String buildCdataContent(final ParseTree.Node node) {
    // cdata_content --> cdata_text+
    // Concatenate all cdata_text tokens without modification
    final var sb = new StringBuilder();

    for (final var child : node.children()) {
      if (child instanceof ParseTree.Leaf leaf) {
        sb.append(leaf.text());
      } else if (child instanceof ParseTree.Node n) {
        final var sym = n.symbol();
        if (sym.equals("cdata_text") || isAux(sym)) {
          sb.append(buildCdataContent(n));
        } else {
          sb.append(getLeafText(n));
        }
      }
    }

    // If node itself is a leaf-containing node, extract directly
    if (sb.isEmpty()) {
      return getLeafText(node);
    }

    return sb.toString();
  }

  private String buildComment(final ParseTree.Node node) {
    // comment --> comment_open comment_text comment_close
    // comment --> comment_open comment_close
    final var sb = new StringBuilder();

    for (final var child : node.children()) {
      if (child instanceof ParseTree.Node n) {
        final var sym = n.symbol();
        if (sym.equals("comment_text") || sym.startsWith("comment_text") && isAux(sym)) {
          sb.append(buildCommentText(n));
        }
      }
    }

    return sb.toString();
  }

  private String buildCommentText(final ParseTree.Node node) {
    // comment_text can be multiple tokens (text chunks and single dashes)
    final var sb = new StringBuilder();

    for (final var child : node.children()) {
      if (child instanceof ParseTree.Leaf leaf) {
        sb.append(leaf.text());
      } else if (child instanceof ParseTree.Node n) {
        final var sym = n.symbol();
        if (sym.equals("comment_text") || isAux(sym)) {
          sb.append(buildCommentText(n));
        } else {
          sb.append(getLeafText(n));
        }
      }
    }

    // If node itself is a leaf-containing node, extract directly
    if (sb.isEmpty()) {
      return getLeafText(node);
    }

    return sb.toString();
  }

  private String buildTextContent(final ParseTree.Node node) {
    // textcontent --> textpart+
    // Concatenate tokens with spaces between alphanumeric words only
    final var sb = new StringBuilder();
    boolean first = true;
    String lastToken = null;

    for (final var child : node.children()) {
      if (child instanceof ParseTree.Node n) {
        final var sym = n.symbol();
        if (sym.equals("textpart") || sym.equals("char_ref") || sym.equals("entity_ref")) {
          final var text = getLeafText(n);
          final var isAlphaNum = text.matches("[a-zA-Z0-9_\\-]+");
          final var lastWasAlphaNum = lastToken != null && lastToken.matches("[a-zA-Z0-9_\\-]+");

          // Add space between two alphanumeric words
          if (!first && isAlphaNum && lastWasAlphaNum) {
            sb.append(" ");
          }

          sb.append(text);
          lastToken = text;
          first = false;
        } else if (isAux(sym)) {
          sb.append(buildTextContent(n));
        }
      }
    }

    return sb.toString();
  }

  private List<XMLNode> buildElementList(final ParseTree.Node node) {
    // element_list --> element+
    final var elements = new ArrayList<XMLNode>();

    for (final var child : node.children()) {
      if (child instanceof ParseTree.Node n) {
        final var sym = n.symbol();
        if (sym.equals("element")) {
          elements.add(buildElement(n));
        } else if (isAux(sym)) {
          elements.addAll(buildElementList(n));
        }
      }
    }

    return elements;
  }

  private String getLeafText(final ParseTree.Node node) {
    return Utilities.textOf(node);
  }

  /**
   * Extracts raw text from original input using parse tree node positions. Returns text between the
   * first and last leaf nodes.
   */
  private String extractRawText(final ParseTree.Node node) {
    final var positions = getNodeBounds(node);
    if (positions != null && input != null) {
      return input.substring(positions[0], positions[1]);
    }
    // Fallback to reconstructed text
    return Utilities.textOf(node);
  }

  /**
   * Gets the start and end positions (in original input) of a parse tree node Returns [start, end]
   * or null if positions unavailable
   */
  private int[] getNodeBounds(final ParseTree node) {
    return switch (node) {
      case ParseTree.Leaf leaf -> new int[] {leaf.start(), leaf.end()};
      case ParseTree.Node n -> {
        int start = Integer.MAX_VALUE;
        int end = Integer.MIN_VALUE;

        for (final var child : n.children()) {
          final var bounds = getNodeBounds(child);
          if (bounds != null) {
            start = Math.min(start, bounds[0]);
            end = Math.max(end, bounds[1]);
          }
        }

        if (start != Integer.MAX_VALUE && end != Integer.MIN_VALUE) {
          yield new int[] {start, end};
        }
        yield null;
      }
    };
  }
}
